version: '1.0.{build}'
skip_tags: true
image:
- Visual Studio 2019
- Ubuntu1804
test: off

environment:
  CLI_VERSION: '5.1.274'
  RUST_TOOLCHAIN: '1.53.0'
  DOCKER_TOKEN:
   secure: QKr2YEuliXdFKe3jN7w97w==
  DOCKER_USER:
    secure: bn3qFcGsm8Qw1V7px12K5w==

init:
  - git config --global core.longpaths true

for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  install:
  - ps: ./ci/win-x64/setup.ps1
  - ps: $env:Path = "C:\Users\appveyor\.cargo\bin;$env:Path"

  build_script:
  - ps: ./ci/win-x64/build.ps1 -shortver "$($env:APPVEYOR_BUILD_VERSION)"

  deploy:
  - provider: NuGet
    api_key:
      secure: FzT5qSphdolME7e5dRSOUptmfdN2sw61jhHxgfH5sUlPIMBT0/5Rw05NB2oKXPLz
    skip_symbols: true
    artifact: /Seq.Input.Syslog.*\.nupkg/
    on:
      branch: /^(dev|release)$/
-
  matrix:
    only:
      - image: Ubuntu1804

  install:
  - ./ci/linux-x64/setup.sh
  - ps: $env:PATH = "/home/appveyor/.cargo/bin:$env:PATH"

  build_script:
  - ps: ./ci/linux-x64/build.ps1 -shortver "$($env:APPVEYOR_BUILD_VERSION)"

artifacts:
- path: publish\*
